### ISSUE TITLE
Fatal error: Class 'TFD_NodeVisitor' not found in /var/www/u4802939/data/www/ortoletto.eterna-e.ru/sites/all/libraries/twig-for-drupal/TFD/Extension.php on line 22

### ISSUE THREAD

**Issue by omcg33** [TFD7/TFD7#10]
After all actions in instruction from GitHub a got this 1
What is this?

**Comment by davidgenetic** [comment]
This is still happening on case-sensitive servers. Changing the filename to NodeVisitor.php (instead of Nodevisitor.php) solves it.

**Comment by ApolloNet** [comment]
Same issue here, renaming solves it.

**Comment by renebakx** [comment]
I thought I renamed it, but I guess i didn't came trough. Just renamed it using the interface here on github, hopefully it sticks this time..
