### ISSUE TITLE
Elaborate on installation procedure/improve examples

### ISSUE THREAD

**Issue by milesblackwood** [TFD7/TFD7#13]
The readme.txt which included previous installation steps seems to be deprecated. This is likely preventing adoption and contribution to the engine. Is that removed information still the required method of installation?

Maybe steps for usage with a simple node template would also be fruitful for the project.

Thanks!

**Comment by renebakx** [comment]
finally found some time to fire up the documentation site, http://tfd7.rocks/install should get the job done. If you find any issues, please let me know.

As for the examples, i'am preparing my base theme for public release. It is the base theme we use at work for al our Drupal sites.

**Comment by milesblackwood** [comment]
Thanks Rene!

**Comment by nolfranklin** [comment]
Great work! Are there any base themes available?
