### ISSUE TITLE
Cached Twig  templates causing Strict warning warnings when getAttributes is called

### ISSUE THREAD

**Issue by chris-hall-hu** [TFD7/TFD7#17]
Thanks for this could be a very useful stepping stone in migration.

Following all the instructions and variations of the examples you gave for adding Twig templates to the Bootstrap theme, everything worked well exept once templates are cached I get:
```Strict warning: Only variables should be passed by reference``` for every line in the cached template that calls getAttribute, because that returns a value not a reference and tfd_render() (which wraps Drupal render()) is expecting a reference to allow hide functionality etc.

I think this is that same issue that had to be addressed in the 'passing by reference' section in this issue: https://www.drupal.org/node/1696786 for Drupal 8 core.

You should be able to see the errors on http://contour-vanilla.codio.io:3000 if no error refresh the page to get the template cached.

With a bit of luck you may be able to see the cached template for html.tpl.twig here: https://codio.com/chris-hall-hu-cheng/Drupal7-twig/tree/sites%2Fdefault%2Ffiles%2Ftwig_cache%2Fsites%2Fall%2Fthemes%2Fbootstrap%2Ftheme%2Fsystem%2Fhtml.tpl.twig.php

BTW happy to help with testing, bug-fixes etc. when I can, a bit tied up right now though.

**Comment by renebakx** [comment]
i suspect this has something todo with me adding the &$vars just before the latest push.. Will look into that later this week.

**Comment by chris-hall-hu** [comment]
Noted your latest commits,  I haven't looked at the show hide filter yet but, it fixes the errors I was getting from cached pages :)
