### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by Ya5in** [TFD7/TFD7#19]
Parse error: syntax error, unexpected '[', expecting ')' in /sites/all/libraries/TFD/TFD/Extension.php on line 479 Call Stack: 0.0001 640672 1. {main}() /index.php:0 0.0933 10998712 2. menu_execute_active_handler() /index.php:23 0.1228 11546688 3. drupal_deliver_page() /includes/menu.inc:542 0.1228 11547280 4. drupal_deliver_html_page() /includes/common.inc:2611 0.1229 11548264 5. drupal_render_page() /includes/common.inc:2729 0.1516 12325848 6. drupal_render() /includes/common.inc:5864 0.1516 12328200 7. theme() /includes/common.inc:6002 0.1586 12426848 8. twig_render_template() /includes/theme.inc:1208 0.1586 12426928 9. twig_get_instance() /sites/all/themes/engines/twig/twig.engine:86 0.1924 13816744 10. Drupal\xautoload\ClassFinder\ClassFinder->loadClass() /sites/all/themes/engines/twig/twig.engine:0 0.1924 13816880 11. Drupal\xautoload\ClassFinder\GenericPrefixMap->loadClass() /sites/all/modules/contrib/xautoload/src/ClassFinder/ClassFinder.php:423

**Comment by renebakx** [comment]
are you perhaps using php 5.3?

I'am using php 5.4 short array construction on that specific line of code.

$blockdata = _block_render_blocks([$block->delta => $block]);

**Comment by Ya5in** [comment]
I am. Thanks for the quick response and the great work!
