### ISSUE TITLE
Fatal error: Class 'TFD_Cache_Filesystem' not found

### ISSUE THREAD

**Issue by hidace** [TFD7/TFD7#39]
Hi, 

Using TFD along with DrupalVM. Install instructions were pretty easy, but when I update my twig engine in my .info file to `engine = twig`, I get a white page with this error: 

`Fatal error: Class 'TFD_Cache_Filesystem' not found`. 

Any thoughts on what it could be? I re-installed twice, but still have this issue. Thanks.

**Comment by renebakx** [comment]
Hi,

Did you enabled x-autolad or used the 3.x-dev branch with composer?

The error sounds like your installation is not able to autoload the needed classes.
